
elektra_request:
    resource:   "@ElektraSiteBundle/Resources/config/routing/request.yml"
    prefix:     /

elektra_admin:
    resource:   "@ElektraSiteBundle/Resources/config/routing/admin.yml"
    prefix:     /admin

# TODO src: add routes for "About", "Terms&Conditions", etc