
_cesu_home:
    path:       /
    defaults:
        _controller:    ElektraSiteBundle:Site:home

_cesu_about:
    path:       /about
    defaults:
        _controller:    ElektraSiteBundle:Site:about


_cesu_terms:
    path:       /terms
    defaults:
        _controller:    ElektraSiteBundle:Site:terms
