# Administrator Home Page
ElektraSiteBundle_admin_index:
    path: /admin
    defaults:
        _controller: ElektraSiteBundle:Admin:index

# Request Page
ElektraSiteBundle_request_index:
    # NOTE: currently only 4 steps are defined - if more are needed, these regex needs to be changed
    # NOTE: steps: "Agree objectives", "Agree T&C", "Enter request data", "Check and submit request data"
    path:       /{step}/{number}
    defaults:
        _controller:    ElektraSiteBundle:Request:steps
        step:           step
        number:         1
    requirements:
        step:           step
        number:         "[1-4]"




# TODO src: add routes for "About", "Terms&Conditions", etc