
parameters:
    elektra_site:
        strings:
            admin:
                menu:
                    master_data: 'Master Data'
                page_name: 'CESU Admin'
                page_title_suffix: 'CESU Administration'
            request:
                menu:
                    none: ''
                page_name: 'TODO: CESU Request'
                page_title_suffix: 'TODO: CESU Request Title Suffix'
