
# User related routing
elektra_user:
    resource:   "@ElektraUserBundle/Resources/config/routing.yml"

# Seed Unit related routing
elektra_seed:
    resource:   "@ElektraSeedBundle/Resources/config/routing.yml"

# Site related routing (Request page, static pages)
elektra_site:
    resource:   "@ElektraSiteBundle/Resources/config/routing.yml"
