
# Import routing.yml from all Elektra packages (if no routing needed, the file will be just empty)

ElektraCrudBundle:
    resource: "@ElektraCrudBundle/Resources/config/routing.yml"

ElektraSeedBundle:
    resource: "@ElektraSeedBundle/Resources/config/routing.yml"

ElektraSiteBundle:
    resource: "@ElektraSiteBundle/Resources/config/routing.yml"

ElektraUserBundle:
    resource: "@ElektraUserBundle/Resources/config/routing.yml"
