security:
    encoders:
        FOS\UserBundle\Model\UserInterface:     sha512

    role_hierarchy:
        ROLE_REPORT_GENERATOR:  ROLE_USER
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        fos_userbundle:
            id:                 fos_user.user_provider.username

    firewalls:
        main:
            pattern:            ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                always_use_default_target_path: true
                use_referer:    true
            logout:             true
            anonymous:          true

#    acl:
#        connection: default

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fonts, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_ADMIN }


#    providers:
#        in_memory:
#            memory: ~
#        fos_userbundle:
#            id: fos_user.user_provider.username
#
#    encoders:
#        FOS\UserBundle\Models\UserInterface: sha512
#
#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#            logout: true
#            anonymous: true
#
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~
