<?php

namespace Elektra\CrudBundle\Form\Field;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

abstract class AbstractListType extends AbstractType
{

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {

        parent::setDefaultOptions($resolver);

        $resolver->setOptional(
            array(
                'list_limit',
                'ordering_field',
                'ordering_direction',
            )
        );
        $resolver->setDefaults(
            array(
                'ordering_direction' => 'DESC',
            )
        );
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {

        $view->vars['list_limit']         = '';
        $view->vars['ordering_field']     = '';
        $view->vars['ordering_direction'] = '';

        if (isset($options['list_limit'])) {
            $view->vars['list_limit'] = $options['list_limit'];
        }
        if (isset($options['ordering_field'])) {
            $view->vars['ordering_field'] = $options['ordering_field'];
        }
        if (isset($options['ordering_direction'])) {
            $view->vars['ordering_direction'] = $options['ordering_direction'];
        }

        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {

        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}