<?php

namespace Elektra\CrudBundle\Form\Field;

use Elektra\CrudBundle\Definition\Definition;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class RelatedListType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function getName()
    {

        return 'relatedList';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {

        parent::setDefaultOptions($resolver);

        //        $resolver->setDefaults(
        //            array(
        //                'definition' => null,
        //            )
        //        );

        $resolver->setRequired(
            array(
                'definition',
                'entity',
                'relation'
            )
        );
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {

        $view->vars['definition'] = $options['definition'];
        $view->vars['entity']     = $options['entity'];
        $view->vars['relation'] = $options['relation'];

        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function finishView(FormView $view, FormInterface $form, array $options)
    {

        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}