<?php

namespace Elektra\SeedBundle\Controller\Companies;

use Elektra\CrudBundle\Controller\Controller;
use Elektra\CrudBundle\Crud\Definition;
use Elektra\SeedBundle\Entity\EntityInterface;
use Symfony\Component\Form\FormInterface;

class CustomerController extends Controller
{

    /**
     * @return Definition
     */
    protected function getDefinition()
    {

        return $this->get('navigator')->getDefinition('Elektra', 'Seed', 'Companies', 'Customer');
    }

    public function beforeAddEntity(EntityInterface $entity, FormInterface $form = null)
    {

        $partnerId = $this->getCrud()->getRequest()->get('id');
        $manager   = $this->getDoctrine()->getManager();
        $partner   = $manager->find($this->getCrud()->getDefinition('Elektra', 'Seed', 'Companies', 'Partner')->getClassEntity(), $partnerId);

        $entity->getPartners()->add($partner);
        $partner->getCustomers()->add($entity);

        return parent::beforeAddEntity($entity, $form); // TODO: Change the autogenerated stub
    }
}