# Define the services provided by the ThemeBundle
services:
    # Form Fields
    elektra_theme.form.type.cancel: # Cancel Form Field
        class: Elektra\ThemeBundle\Form\Field\CancelType
        tags:
            - { name: form.type, alias: cancel }

    elektra_theme.form.type.buttongroup: # Button Group for Forms
        class: Elektra\ThemeBundle\Form\Field\ButtonGroupType
        tags:
            - { name: form.type, alias: buttonGroup }

    # Global page object for theme-specific data
    page:
        class: Elektra\ThemeBundle\Page\Page
        arguments:
            - "@service_container"

    # Twig extensions
    elektra_theme.twig.page_extension:
        class: Elektra\ThemeBundle\Twig\PageExtension
        arguments:
            - "@page"
        tags:
            - { name: twig.extension }
