
services:
    theme:
        class: Elektra\ThemeBundle\Theme\Theme

    elektra.twig.theme_extension:
        class: Elektra\ThemeBundle\Twig\ThemeExtension
        arguments:
            - "@theme"
        tags:
            - { name: twig.extension }