###############################################################################
# @author    Florian Eichler <florian@eichler.co.at>
# @author    Alexander Spengler <alexander.spengler@habanero-it.eu>
# @copyright 2014 Florian Eichler, Alexander Spengler. All rights reserved.
# @license   MINOR add a license
# @version   0.1-dev
###############################################################################

ElektraSeedBundle:
    resource: .
    prefix: /
    type: routing

request.seedUnit.add:
    pattern:  /requests/addUnits/{id}
    defaults: { _controller: ElektraSeedBundle:Requests/Request:addUnit }
