###############################################################################
# @author    Florian Eichler <florian@eichler.co.at>
# @author    Alexander Spengler <alexander.spengler@habanero-it.eu>
# @copyright 2014 Florian Eichler, Alexander Spengler. All rights reserved.
# @license   MINOR add a license
# @version   0.1-dev
###############################################################################

ElektraSeedBundle:
    resource: .
    prefix: /
    type: routing

request.seedUnit.add:
    pattern:  /request/addUnits/{id}/{page}
    defaults: { _controller: ElektraSeedBundle:Requests/Request:addUnit, page: 1 }

seedUnit.addEvent:
    pattern:  /seedUnit/addEvent/{id}
    defaults: { _controller: ElektraSeedBundle:SeedUnits/SeedUnit:addEvent }

request.addEvent:
    pattern:  /request/addEvent/{id}
    defaults: { _controller: ElektraSeedBundle:Requests/Request:addEvent }

imports.template.download:
    pattern:    /importTemplates/download/{identifier}.{format}
    defaults: { _controller: ElektraSeedBundle:Imports/Template:download }