###############################################################################
# @author    Florian Eichler <florian@eichler.co.at>
# @author    Alexander Spengler <alexander.spengler@habanero-it.eu>
# @copyright 2014 Florian Eichler, Alexander Spengler. All rights reserved.
# @license   MINOR add a license
# @version   0.1-dev
###############################################################################

ElektraSeedBundle:
    resource: .
    prefix: /
    type: routing

request.seedUnit.add:
    pattern:  /request/addUnits/{id}/{page}
    defaults: { _controller: ElektraSeedBundle:Requests/Request:addUnit, page: 1 }

seedUnit.changeShippingStatus:
    pattern:  /seedUnit/changeShippingStatus/{id}-{status}
    defaults: { _controller: ElektraSeedBundle:SeedUnits/SeedUnit:changeShippingStatus }

seedUnit.changeSalesStatus:
    pattern:  /seedUnit/changeSalesStatus/{id}-{statusId}
    defaults: { _controller: ElektraSeedBundle:SeedUnits/SeedUnit:changeSalesStatus }

seedUnit.changeUsage:
    pattern:  /seedUnit/changeUsage/{id}-{usageId}
    defaults: { _controller: ElektraSeedBundle:SeedUnits/SeedUnit:changeUsage }

request.changeShippingStatus:
    pattern:  /request/changeShippingStatus/{id}
    defaults: { _controller: ElektraSeedBundle:Requests/Request:changeShippingStatus }