###############################################################################
# @author    Florian Eichler <florian@eichler.co.at>
# @author    Alexander Spengler <alexander.spengler@habanero-it.eu>
# @copyright 2014 Florian Eichler, Alexander Spengler. All rights reserved.
# @license   MINOR add a license
# @version   0.1-dev
###############################################################################

# Define the services provided by the SeedBundle
services:
    elektra_seed.routing_loader:
        class: Elektra\SeedBundle\Routing\Loader
        arguments:
            - "@navigator"
        tags:
            - { name: routing.loader }

    elektra_seed.audits.listener:
        class: Elektra\SeedBundle\Subscribers\AuditListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    elektra_seed.form.request:
        class: Elektra\SeedBundle\Form\Requests\RequestType
        tags:
            - { name: form.type, alias: request }

    elektra_seed.form.flow.request:
        class: Elektra\SeedBundle\Form\Requests\RequestFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, ["@elektra_seed.form.request"] ]

    elektra_seed.request.numberGenerator:
        class: Elektra\SeedBundle\Request\NumberGenerator
        arguments:
            - "@doctrine"

