
services:
    elektra_seed.routing_loader:
        class: Elektra\SeedBundle\Routing\Loader
        arguments:
            - "@navigator"
        tags:
            - { name: routing.loader }

    elektra_seed.audits.listener:
        class: Elektra\SeedBundle\Subscribers\AuditListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    elektra_seed.company_location.listener:
        class: Elektra\SeedBundle\Subscribers\CompanyLocationListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    elektra_seed.company_person.listener:
        class: Elektra\SeedBundle\Subscribers\CompanyPersonListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
