
services:
#    elektra.seed.audits.subscriber:
#        class: Elektra\SeedBundle\Subscribers\AuditSubscriber
#        arguments: ["@security.context"]
#        tags:
#            - { name: doctrine.event_subcriber }

    elektra.seed.audits.listener:
        class: Elektra\SeedBundle\Subscribers\AuditListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }
