# Define the services provided by the SeedBundle
services:
    elektra_seed.routing_loader:
        class: Elektra\SeedBundle\Routing\Loader
        tags:
            - { name: routing.loader }

    elektra_seed.audits.listener:
        class: Elektra\SeedBundle\Subscribers\AuditListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }