
services:
    elektra_seed.routing_loader:
        class: Elektra\SeedBundle\Routing\RoutingLoader
        tags:
            - { name: routing.loader }

    elektra_seed.audits.listener:
        class: Elektra\SeedBundle\Subscribers\AuditListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }


