
services:
    navigator:
        class: Elektra\CrudBundle\Crud\Navigator
        arguments:
            - "@router"

    elektra_crud.twig.table_extension:
        class: Elektra\CrudBundle\Twig\TableExtension
        tags:
            - { name: twig.extension }

    elektra_crud.form.type.relatedList:
        class: Elektra\CrudBundle\Form\Field\RelatedListType
        tags:
            - { name: form.type, alias: relatedList }

    elektra_crud.form.type.list:
        class: Elektra\CrudBundle\Form\Field\ListType
        tags:
            - { name: form.type, alias: list }

    elektra_crud.form.type.selectList:
        class: Elektra\CrudBundle\Form\Field\SelectListType
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: selectList }

    elektra_crud.form.type.entityTable:
        class: Elektra\CrudBundle\Form\Field\EntityTableType
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: entityTable }
