
admin_home:
    path: /
    defaults:
        _controller: ElektraSiteBundle:Admin:index

seedUnitModels:
    resource:   "@ElektraSiteBundle/Resources/config/routing/admin/seedUnitModels.yml"
    prefix:     /seedunits/models

seedUnitPowerCordTypes:
    resource:   "@ElektraSiteBundle/Resources/config/routing/admin/seedUnitPowerCordTypes.yml"
    prefix:     /seedunits/powercords

